name: Publish Package to npmjs
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm i
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        with:
          tag_name: v0.7.${{steps.current_date.outputs.time}}.${{github.run_number}}
          release_name: v0.7.${{steps.current_date.outputs.time}}.${{github.run_number}}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload source to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/1.0.${{steps.current_date.outputs.time}}.${{github.run_number}}-alpha.zip
          asset_content_type: application/zip
          asset_name: 1.0.${{steps.current_date.outputs.time}}.${{github.run_number}}-alpha.zip
